In [91]:
# 감성지수 포함 데이터 파일
import pandas as pd

df = pd.read_csv('senti_score_final.csv', encoding='utf-8')
df

,Unnamed: 0,Unnamed: 0.1,구분,날짜,본문,태그,감성지수
0,0,0,트위터,2019-11-21,@sky22j0423 예전 웨딩 사업하는 친구에게 결혼할 지인을 소개했더니 나에게 ...,대면모임,-21
1,1,1,트위터,2019-11-21,"@ekctu 민노총 니들 집회 할때 김유난 이라는 사람 좀 댈따 해라, 민폐노총아",대면모임,-6
2,2,2,트위터,2019-11-21,찬열 생일파티 대리티켓팅 구합니다 선입금 없이 수고비 받으실분 구해요 ㅜㅜ,대면모임,2
3,3,3,트위터,2019-11-21,대만 여행객들이 모르는 특별한 빙수 맛집들 https://t.co/mTOWJ...,대면모임,-3
4,4,4,트위터,2019-11-21,"학교모임 단톡방에서 선배언니 남편 공유(그 영화 속) 같다며 칭찬하고 있는데, 어휴...",대면모임,-1
...,...,...,...,...,...,...,...
191079,191079,32005,트위터,2020-12-02,코로나 무섭다 재택근무하고싶다,코로나,-5
191080,191080,32006,트위터,2020-12-02,코로나가 어떻게든 끝나면 프랑스 가고 싶어,코로나,-3
191081,191081,32007,트위터,2020-12-02,[코로나19] 대한항공/ 아시아나 항공 인천- 로스앤젤레스 12월 운항 안내 ht...,코로나,-3
191082,191082,32008,트위터,2020-12-02,코로나19가 턱밑까지 치고 올라온 느낌. 북적북적한 기록관이 언제나 가능할까요? ...,코로나,-3
191083,191083,32009,트위터,2020-12-02,"날이 추우면 어른들 부고가 많이 들린다. 코로나 시국이라 조문객도 거의 없고, 있...",코로나,-14

In [ ]:
# 대면모임, 온라인모임, 방역, 규제, 코로나 각 태그별 csv 파일 만들기

In [92]:
is_moim = df['태그'] == '대면모임'
moim = df[is_moim]

moim

,Unnamed: 0,Unnamed: 0.1,구분,날짜,본문,태그,감성지수
0,0,0,트위터,2019-11-21,@sky22j0423 예전 웨딩 사업하는 친구에게 결혼할 지인을 소개했더니 나에게 ...,대면모임,-21
1,1,1,트위터,2019-11-21,"@ekctu 민노총 니들 집회 할때 김유난 이라는 사람 좀 댈따 해라, 민폐노총아",대면모임,-6
2,2,2,트위터,2019-11-21,찬열 생일파티 대리티켓팅 구합니다 선입금 없이 수고비 받으실분 구해요 ㅜㅜ,대면모임,2
3,3,3,트위터,2019-11-21,대만 여행객들이 모르는 특별한 빙수 맛집들 https://t.co/mTOWJ...,대면모임,-3
4,4,4,트위터,2019-11-21,"학교모임 단톡방에서 선배언니 남편 공유(그 영화 속) 같다며 칭찬하고 있는데, 어휴...",대면모임,-1
...,...,...,...,...,...,...,...
35360,35360,35360,트위터,2020-12-02,@rukas777 으와 룸카페 가보고싶었눈데!!,대면모임,-2
35361,35361,35361,트위터,2020-12-02,맛집이네,대면모임,0
35362,35362,35362,트위터,2020-12-02,@Bitter_S2weet 하...ㅋ.............그리고 회식도 없애주세요...,대면모임,-3
35363,35363,35363,트위터,2020-12-02,#무료챗 #광교연애어플 #광교연애어플후기 나인코트 #광교솔로 무공해 #광교탈모관리 ...,대면모임,6
35364,35364,35364,트위터,2020-12-02,@TM_Kein 대환장 파티,대면모임,0

In [93]:
grouped = moim['감성지수'].groupby(moim['날짜'])
b = dict(grouped.count())
day_count = b.values()
a = dict(grouped.mean())
nalja = a.keys()
mean_senti = a.values()
new = pd.DataFrame()
new['날짜'] = nalja
new['날짜카운팅'] = day_count
new['태그'] = '대면모임'
new['감성점수평균'] = mean_senti
new['Indicator'] = new['날짜카운팅'] * new['감성점수평균']
new

             날짜  날짜카운팅    태그    감성점수평균  Indicator
0    2019-11-21     80  대면모임 -4.512500     -361.0
1    2019-11-22     91  대면모임 -5.593407     -509.0
2    2019-11-23     92  대면모임 -6.880435     -633.0
3    2019-11-24     71  대면모임 -1.422535     -101.0
4    2019-11-25     94  대면모임 -3.595745     -338.0
..          ...    ...   ...       ...        ...
373  2020-11-28     81  대면모임 -4.111111     -333.0
374  2020-11-29     69  대면모임 -4.246377     -293.0
375  2020-11-30     51  대면모임 -3.274510     -167.0
376  2020-12-01     59  대면모임 -2.898305     -171.0
377  2020-12-02     69  대면모임 -4.028986     -278.0

[378 rows x 5 columns]

In [94]:
new.to_csv('senti_score_moim.csv', encoding='utf-8-sig')

In [95]:
is_onlinemoim = df['태그'] == '비대면모임'
onlinemoim = df[is_onlinemoim]

onlinemoim

,Unnamed: 0,Unnamed: 0.1,구분,날짜,본문,태그,감성지수
35366,35366,0,트위터,2019-11-21,@silver_1210 내일은 학교를 안가니 집밥을 먹으면 됩니다,비대면모임,-1
35367,35367,1,트위터,2019-11-21,🎉 D-622 🎉 내새꾸 4주간 힘든훈련 받느라 너무 너무 수고 많았고 수료식 미리...,비대면모임,0
35368,35368,2,트위터,2019-11-21,@unniiii 그저께 홈트를 좀 열심히 했더니 그것 때문인가 싶기도 하고ㅜㅜ 여튼...,비대면모임,-8
35369,35369,3,트위터,2019-11-21,"집밥먹고싶어서 집온건데 가족들 다자고있엇 결국 라면,,, https://t.co/...",비대면모임,3
35370,35370,4,트위터,2019-11-21,★4일만 진행★디엠 디지털 상부급수 대용량가습기 13리터 체험단(~11.24) h...,비대면모임,13
...,...,...,...,...,...,...,...
68164,68164,32798,트위터,2020-12-02,"집에서 홈트 하고 혼자서 야외 걷기 조깅 하시는 분들 진짜 다 존경함,,ㅠ",비대면모임,-3
68165,68165,32799,트위터,2020-12-02,그치만 생리도 안하고 생리전 증후군도 없는 시기에 일마치고 체력이 남는 일은 최근의...,비대면모임,-13
68166,68166,32800,트위터,2020-12-02,오늘은 집밥 두번 + 탱귤탱귤 밤새고 아침에 잠들어서 정오쯤 기상 후 일 바짝하고 ...,비대면모임,-17
68167,68167,32801,트위터,2020-12-02,#창빈버블 밤이는 지금 홈트 중이에요! 홈트위터 갈기는 중,비대면모임,-8
68168,68168,32802,트위터,2020-12-02,🍩mister Donut🍩 ・ポン・デ・リング(名前忘れた💦) ・ココナッツチョコレート...,비대면모임,-1

In [96]:
grouped = onlinemoim['감성지수'].groupby(onlinemoim['날짜'])
b = dict(grouped.count())
day_count = b.values()
a = dict(grouped.mean())
nalja = a.keys()
mean_senti = a.values()
new = pd.DataFrame()
new['날짜'] = nalja
new['날짜카운팅'] = day_count
new['태그'] = '비대면모임'
new['감성점수평균'] = mean_senti
new['Indicator'] = new['날짜카운팅'] * new['감성점수평균']
new

             날짜  날짜카운팅     태그    감성점수평균  Indicator
0    2019-11-20     50  비대면모임 -3.480000     -174.0
1    2019-11-21     65  비대면모임 -1.923077     -125.0
2    2019-11-22     87  비대면모임  2.781609      242.0
3    2019-11-23     66  비대면모임  1.045455       69.0
4    2019-11-24     82  비대면모임 -0.012195       -1.0
..          ...    ...    ...       ...        ...
374  2020-11-28     66  비대면모임 -2.651515     -175.0
375  2020-11-29     91  비대면모임 -3.362637     -306.0
376  2020-11-30     80  비대면모임 -4.887500     -391.0
377  2020-12-01     71  비대면모임 -2.901408     -206.0
378  2020-12-02     73  비대면모임 -4.890411     -357.0

[379 rows x 5 columns]

In [97]:
new.to_csv('senti_score_onlinemoim.csv', encoding='utf-8-sig')

In [98]:
is_bangyuk = df['태그'] == '방역'
bangyuk = df[is_bangyuk]

bangyuk

,Unnamed: 0,Unnamed: 0.1,구분,날짜,본문,태그,감성지수
68170,68170,0,트위터,2019-11-21,마스크를 쓰긴 해야겠지...,방역,-5
68171,68171,1,트위터,2019-11-21,"마스크가 제 아티스트만한, 아니 아티스트보다 더 나은 거 같기도 한데 춤은 기가 막...",방역,-11
68172,68172,2,트위터,2019-11-21,@shelbyville402 마스크가더러워질때까지 일하는거네요 지아님 고생하셨어요,방역,-5
68173,68173,3,트위터,2019-11-21,우리 지민이 왔었어ㅠ우리 지민이두 감기조심해ㅠ아프면 절대절대루 안돼ㅠ털모자두쓰구마스...,방역,1
68174,68174,4,트위터,2019-11-21,@RealKaracha 배달 라이더들이 살것 같은 마스크네여,방역,-2
...,...,...,...,...,...,...,...
104675,104675,36505,트위터,2020-12-02,@SUH_dohyeon 정말 어디부터 지적해야할지 알수가없는 마스크지만 어떻게 한...,방역,-10
104676,104676,36506,트위터,2020-12-02,콩떡아 마스크쎠마스크....,방역,-8
104677,104677,36507,트위터,2020-12-02,너무너무 가고 싶네...언제 가지...? 하면서 마스크 콧잔등을 눌러 단단히 잘 했...,방역,-10
104678,104678,36508,트위터,2020-12-02,@Apinkohy 하영아 오늘도 날씨가 추워!! 옷은 꼭꼭 따뜻히 입고 감기는 꼭 ...,방역,-18
104679,104679,36509,트위터,2020-12-02,아 마스크 쓰고 뛰어서 ㅈ하처류타니까 딱 질식사 일보직전,방역,-12

In [99]:
grouped = bangyuk['감성지수'].groupby(bangyuk['날짜'])
b = dict(grouped.count())
day_count = b.values()
a = dict(grouped.mean())
nalja = a.keys()
mean_senti = a.values()
new = pd.DataFrame()
new['날짜'] = nalja
new['날짜카운팅'] = day_count
new['태그'] = '방역'
new['감성점수평균'] = mean_senti
new['Indicator'] = new['날짜카운팅'] * new['감성점수평균']
new

             날짜  날짜카운팅  태그     감성점수평균  Indicator
0    2019-11-21    102  방역  -4.519608     -461.0
1    2019-11-22     98  방역  -8.132653     -797.0
2    2019-11-23     99  방역  -6.636364     -657.0
3    2019-11-24    100  방역  -7.980000     -798.0
4    2019-11-25     93  방역  -7.182796     -668.0
..          ...    ...  ..        ...        ...
373  2020-11-28     88  방역  -7.318182     -644.0
374  2020-11-29     78  방역  -9.679487     -755.0
375  2020-11-30     96  방역 -10.541667    -1012.0
376  2020-12-01    100  방역  -7.920000     -792.0
377  2020-12-02     97  방역  -7.659794     -743.0

[378 rows x 5 columns]

In [100]:
new.to_csv('senti_score_bangyuk.csv', encoding='utf-8-sig')

In [101]:
is_gujea = df['태그'] == '규제'
gujea = df[is_gujea]

gujea

,Unnamed: 0,Unnamed: 0.1,구분,날짜,본문,태그,감성지수
104681,104681,0,트위터,2019-11-23,‘Be Not 시리즈’는 비판적 부정과 거리두기를 통해 참된 앎을 탐색하고자 하는 ...,규제,-14
104682,104682,1,트위터,2020-01-25,이 거리감 두기가 어려워질 때는 오히려 사회적인 구도속에서 이룬 성취감을 느끼거나 ...,규제,-14
104683,104683,2,트위터,2020-02-23,현 상황에 대한 과학기자 강양구 님의 견해. [코로나19: 사회적 거리 두기] (....,규제,-23
104684,104684,3,트위터,2020-02-25,“일상을 유지하되 사회적 거리두기가 필요하다. 외국에서 들어온 사람이 많은 모임을 ...,규제,-38
104685,104685,4,트위터,2020-02-25,열 살짝 나면 집에서 사나흘..'사회적 거리두기' 실천하자 https://t.co/...,규제,-39
...,...,...,...,...,...,...,...
159068,159068,54387,트위터,2020-12-01,ㅏㅣㅓ ㅓㅓㅓ,규제,0
159069,159069,54388,트위터,2020-12-01,사회적 거리두기 예를들면 인사않기,규제,-9
159070,159070,54389,트위터,2020-12-01,@Dear___MG 2미터 떨어져서 걷기로해요 사회적 거리두기,규제,-2
159071,159071,54390,트위터,2020-12-01,@sleeep_sheep 학교야~ 긁밥이가 시키지 않아도 알아서 걸어간거야?,규제,-1
159072,159072,54391,트위터,2020-12-01,줫같은 독뎀때문에 스틱스 가자마자 뒈짐,규제,0

In [102]:
grouped = gujea['감성지수'].groupby(gujea['날짜'])
b = dict(grouped.count())
day_count = b.values()
a = dict(grouped.mean())
nalja = a.keys()
mean_senti = a.values()
new = pd.DataFrame()
new['날짜'] = nalja
new['날짜카운팅'] = day_count
new['태그'] = '규제'
new['감성점수평균'] = mean_senti
new['Indicator'] = new['날짜카운팅'] * new['감성점수평균']
new

             날짜  날짜카운팅  태그     감성점수평균  Indicator
0    2019-11-23      1  규제 -14.000000      -14.0
1    2020-01-25      1  규제 -14.000000      -14.0
2    2020-02-23      1  규제 -23.000000      -23.0
3    2020-02-24      2  규제 -22.500000      -45.0
4    2020-02-25     12  규제 -19.833333     -238.0
..          ...    ...  ..        ...        ...
281  2020-11-28    245  규제  -7.481633    -1833.0
282  2020-11-29    184  규제  -8.788043    -1617.0
283  2020-11-30    218  규제  -8.091743    -1764.0
284  2020-12-01    213  규제  -6.478873    -1380.0
285  2020-12-02    177  규제  -4.107345     -727.0

[286 rows x 5 columns]

In [103]:
new.to_csv('senti_score_gujea.csv', encoding='utf-8-sig')

In [104]:
is_covid = df['태그'] == '코로나'
covid = df[is_covid]

covid

,Unnamed: 0,Unnamed: 0.1,구분,날짜,본문,태그,감성지수
159074,159074,0,트위터,2019-11-21,코로나 염색약이랑 체리 코스튬 땨문에 얼마까지 과금해야하나 셈하다가 그냥 뮤아 엘리...,코로나,-7
159075,159075,1,트위터,2019-11-21,코로나만 하고 다음 색채는 안해야지... https://t.co/EIkxzehTi6,코로나,-4
159076,159076,2,트위터,2019-11-21,나 코로나랑 입히려고 새 옷도 장만함 https://t.co/oX3WpkApRq,코로나,-1
159077,159077,3,트위터,2019-11-21,각칭탄에 코로나가 이렇게 찰떡일 수 없음,코로나,-1
159078,159078,4,트위터,2019-11-21,@FF14_catDoong 오..틔터에서 표... 찾아봐야겠다 ㅠ 코로나 표라고 ...,코로나,3
...,...,...,...,...,...,...,...
191079,191079,32005,트위터,2020-12-02,코로나 무섭다 재택근무하고싶다,코로나,-5
191080,191080,32006,트위터,2020-12-02,코로나가 어떻게든 끝나면 프랑스 가고 싶어,코로나,-3
191081,191081,32007,트위터,2020-12-02,[코로나19] 대한항공/ 아시아나 항공 인천- 로스앤젤레스 12월 운항 안내 ht...,코로나,-3
191082,191082,32008,트위터,2020-12-02,코로나19가 턱밑까지 치고 올라온 느낌. 북적북적한 기록관이 언제나 가능할까요? ...,코로나,-3
191083,191083,32009,트위터,2020-12-02,"날이 추우면 어른들 부고가 많이 들린다. 코로나 시국이라 조문객도 거의 없고, 있...",코로나,-14

In [105]:
grouped = covid['감성지수'].groupby(covid['날짜'])
b = dict(grouped.count())
day_count = b.values()
a = dict(grouped.mean())
nalja = a.keys()
mean_senti = a.values()
new = pd.DataFrame()
new['날짜'] = nalja
new['날짜카운팅'] = day_count
new['태그'] = '코로나'
new['감성점수평균'] = mean_senti
new['Indicator'] = new['날짜카운팅'] * new['감성점수평균']
new

             날짜  날짜카운팅   태그     감성점수평균  Indicator
0    2019-11-21    189  코로나  -0.169312      -32.0
1    2019-11-22     54  코로나  -0.685185      -37.0
2    2019-11-23     45  코로나  -1.822222      -82.0
3    2019-11-24     31  코로나  -3.000000      -93.0
4    2019-11-25     28  코로나  -2.000000      -56.0
..          ...    ...  ...        ...        ...
373  2020-11-28     92  코로나 -11.641304    -1071.0
374  2020-11-29     64  코로나  -9.125000     -584.0
375  2020-11-30     70  코로나  -8.642857     -605.0
376  2020-12-01     85  코로나  -8.058824     -685.0
377  2020-12-02     86  코로나  -9.372093     -806.0

[378 rows x 5 columns]

In [106]:
new.to_csv('senti_score_covid.csv', encoding='utf-8-sig')