In [13]:
from os import listdir
from os.path import isfile, join
import json
from pandas import Series, DataFrame
import pandas as pd

new_df = pd.DataFrame()

#file open_learning data file 
df = pd.read_csv('correlation_result_data.csv', encoding='utf-8')
df

,Unnamed: 0,date,ftof_meeting,ftof_meeting_rate,prevention,prevention_rate,regulation,regulation_rate,covid_num
0,1,2019-11-22,-509,NaN,-797,NaN,0,NaN,0
1,2,2019-11-23,-633,-24%,-657,18%,-14,NaN,0
2,3,2019-11-24,-101,84%,-798,-21%,0,NaN,0
3,4,2019-11-25,-338,-235%,-668,16%,0,NaN,0
4,5,2019-11-26,-493,-46%,-609,9%,0,NaN,0
...,...,...,...,...,...,...,...,...,...
372,373,2020-11-28,-333,-65%,-644,33%,-1833,-45%,488
373,374,2020-11-29,-293,12%,-755,-17%,-1617,12%,449
374,375,2020-11-30,-167,43%,-1012,-34%,-1764,-9%,377
375,376,2020-12-01,-171,-2%,-792,22%,-1380,22%,451
376,377,2020-12-02,-278,-63%,-743,6%,-727,47%,511

In [15]:
df[['ftof_meeting', 'ftof_meeting_rate', 'covid_num']]

     ftof_meeting ftof_meeting_rate  covid_num
0            -509               NaN          0
1            -633              -24%          0
2            -101               84%          0
3            -338             -235%          0
4            -493              -46%          0
..            ...               ...        ...
372          -333              -65%        488
373          -293               12%        449
374          -167               43%        377
375          -171               -2%        451
376          -278              -63%        511

[377 rows x 3 columns]

In [17]:
a = df['ftof_meeting_rate'].tolist()
a

[nan,
 '-24%',
 '84%',
 '-235%',
 '-46%',
 '33%',
 '-54%',
 '34%',
 '65%',
 '-99%',
 '-223%',
 '42%',
 '5%',
 '11%',
 '58%',
 '-13%',
 '-98%',
 '-14%',
 '25%',
 '-59%',
 '72%',
 '-172%',
 '-35%',
 '-25%',
 '18%',
 '36%',
 '67%',
 '-85%',
 '29%',
 '24%',
 '-62%',
 '38%',
 '-58%',
 '10%',
 '53%',
 '-139%',
 '-424%',
 '-11%',
 '84%',
 '7%',
 '-109%',
 '-15%',
 '18%',
 '69%',
 '-213%',
 '55%',
 '-58%',
 '20%',
 '57%',
 '-367%',
 '19%',
 '-26%',
 '-14%',
 '97%',
 '-2136%',
 '34%',
 '-34%',
 '-79%',
 '7%',
 '-4%',
 '-27%',
 '71%',
 '-80%',
 '26%',
 '-3%',
 '-57%',
 '23%',
 '-17%',
 '-40%',
 '8%',
 '-22%',
 '-20%',
 '-19%',
 '94%',
 '-411%',
 '14%',
 '-29%',
 '-3%',
 '-1%',
 '28%',
 '-80%',
 '38%',
 '-44%',
 '-5%',
 '22%',
 '-30%',
 '-2%',
 '-19%',
 '-3%',
 '-41%',
 '-15%',
 '-56%',
 '22%',
 '-14%',
 '-9%',
 '35%',
 '-101%',
 '22%',
 '33%',
 '27%',
 '-24%',
 '-31%',
 '54%',
 '23%',
 '-29%',
 '18%',
 '-45%',
 '-123%',
 '72%',
 '-189%',
 '61%',
 '-178%',
 '43%',
 '-61%',
 '46%',
 '29%',
 '-109%',
 '67%',
 '-74%',
 '-30%',
 '-18%',
 '3%',
 '-24%',
 '37%',
 '11%',
 '65%',
 '-165%',
 '47%',
 '-235%',
 '81%',
 '-255%',
 '2%',
 '-14%',
 '13%',
 '85%',
 '-129%',
 '-213%',
 '15%',
 '67%',
 '-83%',
 '15%',
 '-61%',
 '-90%',
 '56%',
 '12%',
 '-39%',
 '-73%',
 '50%',
 '-122%',
 '39%',
 '52%',
 '-110%',
 '-38%',
 '63%',
 '-191%',
 '53%',
 '-98%',
 '55%',
 '3%',
 '-81%',
 '-49%',
 '49%',
 '46%',
 '-48%',
 '7%',
 '-326%',
 '57%',
 '76%',
 '-237%',
 '-95%',
 '35%',
 '15%',
 '11%',
 '-17%',
 '-34%',
 '-26%',
 '28%',
 '-5%',
 '12%',
 '-15%',
 '12%',
 '-86%',
 '67%',
 '-215%',
 '89%',
 '-255%',
 '3%',
 '-47%',
 '57%',
 '38%',
 '-89%',
 '72%',
 '-52%',
 '-356%',
 '-10%',
 '41%',
 '-28%',
 '40%',
 '-129%',
 '142%',
 '-204%',
 '-7%',
 '-12%',
 '-42%',
 '17%',
 '27%',
 '22%',
 '-86%',
 '78%',
 '-595%',
 '-189%',
 '81%',
 '-21%',
 '39%',
 '-1040%',
 '90%',
 '-85%',
 '50%',
 '-10%',
 '68%',
 '270%',
 '-289%',
 '-14%',
 '-2%',
 '19%',
 '612%',
 '-133%',
 '50%',
 '19%',
 '-27%',
 '-90%',
 '-1%',
 '38%',
 '-91%',
 '54%',
 '5%',
 '-48%',
 '-91%',
 '48%',
 '-105%',
 '47%',
 '-35%',
 '9%',
 '9%',
 '54%',
 '-13%',
 '-25%',
 '-57%',
 '45%',
 '-143%',
 '46%',
 '-19%',
 '35%',
 '26%',
 '-79%',
 '91%',
 '-887%',
 '11%',
 '-44%',
 '27%',
 '-29%',
 '24%',
 '2%',
 '-26%',
 '-2%',
 '-8%',
 '-28%',
 '-84%',
 '-79%',
 '8%',
 '-1%',
 '-20%',
 '7%',
 '-44%',
 '22%',
 '6%',
 '39%',
 '-2%',
 '37%',
 '-105%',
 '27%',
 '3%',
 '7%',
 '9%',
 '21%',
 '-93%',
 '-6%',
 '51%',
 '-115%',
 '-5%',
 '6%',
 '47%',
 '35%',
 '-12%',
 '-34%',
 '-49%',
 '53%',
 '20%',
 '20%',
 '-21%',
 '-72%',
 '-43%',
 '63%',
 '15%',
 '-4%',
 '93%',
 '-5065%',
 '20%',
 '26%',
 '-6%',
 '2%',
 '-68%',
 '49%',
 '-1%',
 '37%',
 '-212%',
 '13%',
 '-63%',
 '65%',
 '24%',
 '-70%',
 '36%',
 '-55%',
 '39%',
 '-3%',
 '-3%',
 '-42%',
 '38%',
 '26%',
 '-112%',
 '62%',
 '63%',
 '-161%',
 '36%',
 '18%',
 '-361%',
 '56%',
 '-56%',
 '-20%',
 '3%',
 '53%',
 '-32%',
 '-39%',
 '-5%',
 '48%',
 '-55%',
 '-3%',
 '20%',
 '-117%',
 '62%',
 '-74%',
 '21%',
 '49%',
 '-177%',
 '-38%',
 '65%',
 '107%',
 '-5091%',
 '85%',
 '31%',
 '13%',
 '-131%',
 '115%',
 '-841%',
 '-38%',
 '-9%',
 '-13%',
 '14%',
 '32%',
 '-18%',
 '-61%',
 '15%',
 '-65%',
 '12%',
 '43%',
 '-2%',
 '-63%']